#! /bin/sh

echo "Is it morning? Please answet yes or no"
read timeofday

case "$timeofday" in 
yes | YES | Yes | y ) echo "Good morning" ;;
n* | N* )    echo "Good afternoon";;
*   ) echo "sorry, answer not recognized";;
esac

exit 0
